[[libportaudio_ringbuffer]]
arch = "armv7l"
git-tree-sha1 = "7942789e068cabdffb67031c0409e7e13c14b7e0"
libc = "glibc"
os = "linux"

    [[libportaudio_ringbuffer.download]]
    sha256 = "791f0f6d0bb5f6a3a6ebffe539c3520e15f84a1e2dea824e42c57dea02d934c4"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_ringbuffer_jll.jl/releases/download/libportaudio_ringbuffer-v19.6.0+0/libportaudio_ringbuffer.v19.6.0.arm-linux-gnueabihf.tar.gz"
[[libportaudio_ringbuffer]]
arch = "x86_64"
git-tree-sha1 = "8580f32133a594f7386c29852e8cf056dc9ad680"
libc = "glibc"
os = "linux"

    [[libportaudio_ringbuffer.download]]
    sha256 = "e6539576c6fc9975825b8438ce649cbe51675ff7e99516516d538e90a3526564"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_ringbuffer_jll.jl/releases/download/libportaudio_ringbuffer-v19.6.0+0/libportaudio_ringbuffer.v19.6.0.x86_64-linux-gnu.tar.gz"
[[libportaudio_ringbuffer]]
arch = "aarch64"
git-tree-sha1 = "e7c778077ea5e54725099a690768c3d0b41b78d8"
libc = "musl"
os = "linux"

    [[libportaudio_ringbuffer.download]]
    sha256 = "2270d5c4c3b0a61e6e2d0066f3e2096c39769d4d97588043c98b676ce9016b54"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_ringbuffer_jll.jl/releases/download/libportaudio_ringbuffer-v19.6.0+0/libportaudio_ringbuffer.v19.6.0.aarch64-linux-musl.tar.gz"
[[libportaudio_ringbuffer]]
arch = "powerpc64le"
git-tree-sha1 = "9e3e8b074690c1ba8d3cd77fdd354767a65846b3"
libc = "glibc"
os = "linux"

    [[libportaudio_ringbuffer.download]]
    sha256 = "7125dc8d5161fdbf89bea10a9238fac921737d490c9aa375ccde139f118a6430"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_ringbuffer_jll.jl/releases/download/libportaudio_ringbuffer-v19.6.0+0/libportaudio_ringbuffer.v19.6.0.powerpc64le-linux-gnu.tar.gz"
[[libportaudio_ringbuffer]]
arch = "x86_64"
git-tree-sha1 = "0cce19111d8523c9e4b5487bdc67715eac3d740b"
os = "macos"

    [[libportaudio_ringbuffer.download]]
    sha256 = "82a429733df97be127055aae6f5ada7f731b542c0c504ce305780c1193973239"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_ringbuffer_jll.jl/releases/download/libportaudio_ringbuffer-v19.6.0+0/libportaudio_ringbuffer.v19.6.0.x86_64-apple-darwin14.tar.gz"
[[libportaudio_ringbuffer]]
arch = "x86_64"
git-tree-sha1 = "487a1611bba670f573c084fbfbea9ef8d74da5eb"
libc = "musl"
os = "linux"

    [[libportaudio_ringbuffer.download]]
    sha256 = "12eb80b6663903861ede63c109e8cd53f6f0d504d1163b32e9222857a68f2a85"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_ringbuffer_jll.jl/releases/download/libportaudio_ringbuffer-v19.6.0+0/libportaudio_ringbuffer.v19.6.0.x86_64-linux-musl.tar.gz"
[[libportaudio_ringbuffer]]
arch = "x86_64"
git-tree-sha1 = "8ba84b9baa95b5cd6de21b68a312138816dbc681"
os = "windows"

    [[libportaudio_ringbuffer.download]]
    sha256 = "1ee0be9014c5e312a116705acc79df04f93fce12a43ad8169f02220ce2e94eb0"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_ringbuffer_jll.jl/releases/download/libportaudio_ringbuffer-v19.6.0+0/libportaudio_ringbuffer.v19.6.0.x86_64-w64-mingw32.tar.gz"
[[libportaudio_ringbuffer]]
arch = "i686"
git-tree-sha1 = "8e9720c95e4b7472c84df10fb6e717e469e974fe"
libc = "glibc"
os = "linux"

    [[libportaudio_ringbuffer.download]]
    sha256 = "306bf82e41c6e735311d81d13eaac7dd68915333695ef9123680ca1e17725830"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_ringbuffer_jll.jl/releases/download/libportaudio_ringbuffer-v19.6.0+0/libportaudio_ringbuffer.v19.6.0.i686-linux-gnu.tar.gz"
[[libportaudio_ringbuffer]]
arch = "aarch64"
git-tree-sha1 = "32acafc052196e558ce5578afebb48e325996a65"
libc = "glibc"
os = "linux"

    [[libportaudio_ringbuffer.download]]
    sha256 = "e4c92087699b606b7c3320c80b09e3706c9fff48f31395e8f3f46378db7343c0"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_ringbuffer_jll.jl/releases/download/libportaudio_ringbuffer-v19.6.0+0/libportaudio_ringbuffer.v19.6.0.aarch64-linux-gnu.tar.gz"
[[libportaudio_ringbuffer]]
arch = "i686"
git-tree-sha1 = "2df849be0ccc1c53f0c106aaf8f9ca4719eda60c"
libc = "musl"
os = "linux"

    [[libportaudio_ringbuffer.download]]
    sha256 = "c83b17aee62d5b15fc4f414c7d49e1ea0181b571965979f0b5659dcddaa202a3"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_ringbuffer_jll.jl/releases/download/libportaudio_ringbuffer-v19.6.0+0/libportaudio_ringbuffer.v19.6.0.i686-linux-musl.tar.gz"
[[libportaudio_ringbuffer]]
arch = "x86_64"
git-tree-sha1 = "8796584aefee295638afc6dd3b052116149c8941"
os = "freebsd"

    [[libportaudio_ringbuffer.download]]
    sha256 = "32278102cff512d01e1e408ce7300a5d9f27142accf93a504a10e12555712d6b"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_ringbuffer_jll.jl/releases/download/libportaudio_ringbuffer-v19.6.0+0/libportaudio_ringbuffer.v19.6.0.x86_64-unknown-freebsd11.1.tar.gz"
[[libportaudio_ringbuffer]]
arch = "i686"
git-tree-sha1 = "2b80bec30592dca27c14ad81861bf0d4c500905a"
os = "windows"

    [[libportaudio_ringbuffer.download]]
    sha256 = "7abed0d02c9e88e6c8fe21f9a12ebd24416ee5b27df8dbd3107285f2068ffcbd"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_ringbuffer_jll.jl/releases/download/libportaudio_ringbuffer-v19.6.0+0/libportaudio_ringbuffer.v19.6.0.i686-w64-mingw32.tar.gz"
[[libportaudio_ringbuffer]]
arch = "armv7l"
git-tree-sha1 = "3bb2c49fa1698bf4dfd4a2d6edd62b3cea727739"
libc = "musl"
os = "linux"

    [[libportaudio_ringbuffer.download]]
    sha256 = "15d696f6d39e5a35e8eae81f990c39aa70e949ff7c94d917da90e0ecd4459355"
    url = "https://github.com/JuliaBinaryWrappers/libportaudio_ringbuffer_jll.jl/releases/download/libportaudio_ringbuffer-v19.6.0+0/libportaudio_ringbuffer.v19.6.0.arm-linux-musleabihf.tar.gz"
